### ISSUE TITLE
Clarify section on PLS-DA and sPLS-DA

### ISSUE THREAD

**Issue by GegznaV** [mixOmicsTeam/Bookdown#2]
In "Quick start" and the further sections of chapter 4 ([link](https://mixomicsteam.github.io/Bookdown/plsda.html#quick-start-1)) descriptions and code of PLS-DA and sPLS-DA are mixed thus it's confusing to understand.
The example code does not work out of the box. E.g., object `MyResult.splsda` is not defined.

Could you make a more clear distinction between PLS-DA and sPLS-DA in the narration and give code examples for both methods that work out of the box?

**Comment by ajabadi** [comment]
Hi @GegznaV,

Thanks for pointing out the issue in the vignette which we will fix immediately.

You can follow our reproducible examples on the PLS-DA and sPLS-DA (and many more) in detail via [this link](http://mixomics.org/methods/pls-da/). Feel free to check out other examples too if you find them useful in your analyses.

Put simply, sPLS-DA (*sparse* PLS-DA) is a version of the PLS-DA method that tries to discriminate between the classes *only using a subset of features on each component* to favour interpretability. More clarification can be found in the [vignette](https://mixomicsteam.github.io/Bookdown/pls.html#pls).

Thanks for using mixOmics!

**Comment by ajabadi** [comment]
This is resolved now and the updated vignette should be easier to follow.
> The example code does not work out of the box. E.g., object `MyResult.splsda` is not defined.

Please feel free to check out our [discussion forum](https://mixomics-users.discourse.group/) and submit your questions there.
